import { Product, Category, Collection, HomepageCMS } from '@/types';

export const initialCategories: Category[] = [
  {
    id: 'cat-tops',
    slug: 'tops',
    name: 'Tops',
    description: 'Elevated basic tees, satin blouses, ribbed crops & knitwear crafted for everyday style.',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
    subcategories: ['Basic Tops', 'Crop Tops', 'Ribbed Tops', 'Shirts', 'Blouses', 'Tank Tops'],
  },
  {
    id: 'cat-dresses',
    slug: 'dresses',
    name: 'Dresses',
    description: 'Effortless mini, midi, and maxi dresses designed to make a confident statement.',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop',
    subcategories: ['Mini Dresses', 'Midi Dresses', 'Maxi Dresses', 'Casual Dresses', 'Party Dresses'],
  },
  {
    id: 'cat-bottoms',
    slug: 'bottoms',
    name: 'Bottoms',
    description: 'Tailored trousers, high-waisted denim, cargo pants & chic skirts.',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
    subcategories: ['Jeans', 'Trousers', 'Cargo Pants', 'Skirts', 'Shorts'],
  },
  {
    id: 'cat-sets',
    slug: 'sets',
    name: 'Sets',
    description: 'Matching two-piece co-ords and tailored lounge sets for instant coordination.',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
    subcategories: ['Co-ord Sets', 'Two Piece Sets', 'Casual Sets'],
  },
];

export const initialCollections: Collection[] = [
  {
    id: 'col-everyday',
    slug: 'everyday-essentials',
    name: 'Everyday Essentials',
    description: 'Minimalist foundation pieces you will reach for daily.',
    image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'col-party',
    slug: 'party-edits',
    name: 'Party Edits',
    description: 'Satin silhouettes, structured mini dresses and glamorous night-out looks.',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'col-office',
    slug: 'office-formal',
    name: 'Office & Formal',
    description: 'Sleek trousers, sharp blazers and elegant poplin button-downs.',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'col-casual',
    slug: 'casual-chic',
    name: 'Casual Chic',
    description: 'Relaxed fits, rib-knit co-ords and laid-back sophistication.',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'col-weekend',
    slug: 'weekend-looks',
    name: 'Weekend Looks',
    description: 'Breezy linen sets and effortless maxi dresses for weekend ease.',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000&auto=format&fit=crop',
  },
];

export const seedProducts: Product[] = [
  // TOPS (8 products)
  {
    id: 'prod-1',
    slug: 'ribbed-fitted-crop-top',
    name: 'Ribbed Contour Crop Top',
    description: 'Sculpting rib-knit crop top with a classic round neckline. Designed for all-day comfort and effortless layering.',
    details: ['95% Premium Cotton, 5% Elastane', 'Form-fitting rib architecture', 'Soft breathable weave', 'Machine wash cold'],
    fabricCare: 'Hand wash or dry clean recommended. Lay flat to dry.',
    category: 'tops',
    subcategory: 'Crop Tops',
    collections: ['new-arrivals', 'trending', 'everyday-essentials'],
    price: 1599,
    salePrice: 1299,
    discountPercentage: 18,
    rating: 4.8,
    reviewCount: 34,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isSale: true,
    sku: 'ACE-TOP-001',
    createdAt: '2026-03-01T10:00:00.000Z',
    colors: [
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1503342394128-c104d54dba01?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Beige',
        code: '#E3D8C8',
        images: [
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'White',
        code: '#FFFFFF',
        images: [
          'https://images.unsplash.com/photo-1554568218-0f1715e72254?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 12 },
      { size: 'S', stock: 18 },
      { size: 'M', stock: 25 },
      { size: 'L', stock: 10 },
      { size: 'XL', stock: 0 },
      { size: 'XXL', stock: 4 },
    ],
    reviews: [
      {
        id: 'rev-1',
        userName: 'Aayusha K.',
        rating: 5,
        comment: 'The quality of the rib fabric is unmatched! Fits like a dream.',
        createdAt: '2026-03-12',
        verifiedPurchase: true,
      },
      {
        id: 'rev-2',
        userName: 'Sneha R.',
        rating: 4,
        comment: 'Super soft material and very flattering crop length.',
        createdAt: '2026-03-15',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'prod-2',
    slug: 'satin-drape-wrap-blouse',
    name: 'Silk Touch Drape Wrap Blouse',
    description: 'Fluid satin wrap blouse featuring subtle shoulder gathers and an adjustable waist tie for a sleek polished finish.',
    details: ['100% High-grade Polyester Satin', 'Adjustable wrap tie', 'V-neckline', 'Gentle machine wash'],
    fabricCare: 'Cool iron on reverse side. Do not bleach.',
    category: 'tops',
    subcategory: 'Blouses',
    collections: ['best-sellers', 'office-formal', 'party-edits'],
    price: 2499,
    rating: 4.9,
    reviewCount: 52,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isSale: false,
    sku: 'ACE-TOP-002',
    createdAt: '2026-02-15T10:00:00.000Z',
    colors: [
      {
        name: 'Pink',
        code: '#E8A598',
        images: [
          'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 5 },
      { size: 'S', stock: 15 },
      { size: 'M', stock: 20 },
      { size: 'L', stock: 14 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-3',
    slug: 'oversized-poplin-boyfriend-shirt',
    name: 'Oversized Poplin Cotton Shirt',
    description: 'Tailored oversized poplin button-down shirt with a crisp collar and elongated cuffs. The ultimate wardrobe essential.',
    details: ['100% Organic Cotton Poplin', 'Relaxed boyfriend silhouette', 'Mother of pearl effect buttons'],
    fabricCare: 'Machine wash warm. Tumble dry low.',
    category: 'tops',
    subcategory: 'Shirts',
    collections: ['new-arrivals', 'everyday-essentials', 'office-formal'],
    price: 2199,
    salePrice: 1899,
    discountPercentage: 14,
    rating: 4.7,
    reviewCount: 28,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    isSale: true,
    sku: 'ACE-TOP-003',
    createdAt: '2026-03-05T10:00:00.000Z',
    colors: [
      {
        name: 'White',
        code: '#FFFFFF',
        images: [
          'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Blue',
        code: '#8EA7C6',
        images: [
          'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1589310243389-96a5483213a8?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 9 },
      { size: 'XL', stock: 6 },
      { size: 'XXL', stock: 2 },
    ],
  },
  {
    id: 'prod-4',
    slug: 'cropped-knit-cardigan-top',
    name: 'Soft Knit Button-Up Cardigan',
    description: 'Fine-gauge knit top featuring tortoiseshell buttons and rib trim cuffs. Elegant solo or worn open.',
    details: ['70% Viscose, 30% Nylon', 'Delicate pearl knit weave', 'Ribbed hems'],
    fabricCare: 'Hand wash cold. Dry flat.',
    category: 'tops',
    subcategory: 'Ribbed Tops',
    collections: ['casual-chic', 'weekend-looks'],
    price: 1999,
    rating: 4.6,
    reviewCount: 19,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    isSale: false,
    sku: 'ACE-TOP-004',
    createdAt: '2026-02-20T10:00:00.000Z',
    colors: [
      {
        name: 'Brown',
        code: '#7A5C43',
        images: [
          'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Grey',
        code: '#9E9E9E',
        images: [
          'https://images.unsplash.com/photo-1520591799316-6b30425429aa?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 4 },
      { size: 'S', stock: 10 },
      { size: 'M', stock: 14 },
      { size: 'L', stock: 8 },
      { size: 'XL', stock: 3 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-5',
    slug: 'essential-ribbed-tank-top',
    name: 'Minimal Ribbed Scoop Tank',
    description: 'Ultra-versatile scoop neck tank crafted from soft stretch cotton ribbing.',
    details: ['90% Cotton, 10% Elastane', 'Scoop neckline', 'Dual stitching along seams'],
    fabricCare: 'Machine wash with similar colors.',
    category: 'tops',
    subcategory: 'Tank Tops',
    collections: ['everyday-essentials', 'casual-chic'],
    price: 999,
    salePrice: 799,
    discountPercentage: 20,
    rating: 4.9,
    reviewCount: 88,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isSale: true,
    sku: 'ACE-TOP-005',
    createdAt: '2026-01-10T10:00:00.000Z',
    colors: [
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'White',
        code: '#FFFFFF',
        images: [
          'https://images.unsplash.com/photo-1554568218-0f1715e72254?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 20 },
      { size: 'S', stock: 30 },
      { size: 'M', stock: 40 },
      { size: 'L', stock: 25 },
      { size: 'XL', stock: 15 },
      { size: 'XXL', stock: 10 },
    ],
  },
  {
    id: 'prod-6',
    slug: 'lace-detail-sheer-blouse',
    name: 'Lace Inset Romantic Blouse',
    description: 'Delicate blouse with fine lace paneling and subtle balloon sleeves for a dreamy feminine aesthetic.',
    details: ['100% Chiffon Poly with Cotton Lace trim', 'Button cuffs', 'Keyhole back closure'],
    fabricCare: 'Hand wash recommended.',
    category: 'tops',
    subcategory: 'Blouses',
    collections: ['party-edits', 'new-arrivals'],
    price: 2699,
    rating: 4.7,
    reviewCount: 14,
    isTrending: false,
    isNewArrival: true,
    isBestSeller: false,
    isSale: false,
    sku: 'ACE-TOP-006',
    createdAt: '2026-03-08T10:00:00.000Z',
    colors: [
      {
        name: 'White',
        code: '#FFFFFF',
        images: [
          'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 6 },
      { size: 'S', stock: 10 },
      { size: 'M', stock: 12 },
      { size: 'L', stock: 5 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
  },

  // DRESSES (8 products)
  {
    id: 'prod-7',
    slug: 'satin-cowl-neck-mini-dress',
    name: 'Aria Satin Cowl Mini Dress',
    description: 'Sophisticated cowl neck mini dress crafted in high-sheen liquid satin with adjustable criss-cross straps.',
    details: ['100% Premium Satin', 'Cowl neckline', 'Concealed side zipper', 'Fully lined body'],
    fabricCare: 'Dry clean only.',
    category: 'dresses',
    subcategory: 'Mini Dresses',
    collections: ['trending', 'party-edits', 'best-sellers'],
    price: 3499,
    salePrice: 2899,
    discountPercentage: 17,
    rating: 4.9,
    reviewCount: 67,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isSale: true,
    sku: 'ACE-DRS-001',
    createdAt: '2026-02-01T10:00:00.000Z',
    colors: [
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Red',
        code: '#9E2A2B',
        images: [
          'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Emerald Green',
        code: '#1B4D3E',
        images: [
          'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 4 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 18 },
      { size: 'L', stock: 9 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
    reviews: [
      {
        id: 'rev-3',
        userName: 'Prashansa M.',
        rating: 5,
        comment: 'Wore this to a birthday party and got so many compliments! Stretches just enough.',
        createdAt: '2026-03-01',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'prod-8',
    slug: 'ribbed-bodycon-midi-dress',
    name: 'Minimal Ribbed Bodycon Midi',
    description: 'Streamlined midi dress featuring a structured rib texture, high slit design, and flattering scoop neck.',
    details: ['88% Cotton, 12% Spandex', 'Side slit accent', 'Ankle length midi cut'],
    fabricCare: 'Machine wash cold inside out.',
    category: 'dresses',
    subcategory: 'Midi Dresses',
    collections: ['new-arrivals', 'everyday-essentials'],
    price: 2899,
    rating: 4.8,
    reviewCount: 41,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isSale: false,
    sku: 'ACE-DRS-002',
    createdAt: '2026-03-04T10:00:00.000Z',
    colors: [
      {
        name: 'Beige',
        code: '#D4C4B5',
        images: [
          'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1554568218-0f1715e72254?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 16 },
      { size: 'M', stock: 22 },
      { size: 'L', stock: 11 },
      { size: 'XL', stock: 5 },
      { size: 'XXL', stock: 1 },
    ],
  },
  {
    id: 'prod-9',
    slug: 'floral-tiered-tier-maxi-dress',
    name: 'Boho Floral Chiffon Maxi Dress',
    description: 'Ethereal tiered maxi dress adorned with romantic botanical prints, subtle puff sleeves, and a tiered ruffle skirt.',
    details: ['100% Breathable Chiffon', 'Elasticated waist', 'Lined through body'],
    fabricCare: 'Hand wash gently in cold water.',
    category: 'dresses',
    subcategory: 'Maxi Dresses',
    collections: ['weekend-looks', 'casual-chic'],
    price: 3999,
    salePrice: 3299,
    discountPercentage: 17,
    rating: 4.7,
    reviewCount: 23,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isSale: true,
    sku: 'ACE-DRS-003',
    createdAt: '2026-02-10T10:00:00.000Z',
    colors: [
      {
        name: 'Pink Floral',
        code: '#E8A598',
        images: [
          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 3 },
      { size: 'S', stock: 9 },
      { size: 'M', stock: 14 },
      { size: 'L', stock: 7 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-10',
    slug: 'linen-button-down-shirt-dress',
    name: 'Linen Blend Utility Shirt Dress',
    description: 'Breezy linen shirt dress with a removable waist belt, chest patch pockets, and cuffed elbow sleeves.',
    details: ['55% Linen, 45% Cotton', 'Functional button placket', 'Side seam pockets'],
    fabricCare: 'Cool wash. Line dry in shade.',
    category: 'dresses',
    subcategory: 'Casual Dresses',
    collections: ['weekend-looks', 'everyday-essentials'],
    price: 3199,
    rating: 4.8,
    reviewCount: 38,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isSale: false,
    sku: 'ACE-DRS-004',
    createdAt: '2026-03-07T10:00:00.000Z',
    colors: [
      {
        name: 'White',
        code: '#FFFFFF',
        images: [
          'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Beige',
        code: '#E3D8C8',
        images: [
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 6 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 18 },
      { size: 'L', stock: 10 },
      { size: 'XL', stock: 4 },
      { size: 'XXL', stock: 1 },
    ],
  },
  {
    id: 'prod-11',
    slug: 'sculpt-off-shoulder-party-dress',
    name: 'Off-Shoulder Sculpted Mini',
    description: 'Head-turning off-shoulder mini dress featuring contour seam detail and a boned bodice for total support.',
    details: ['92% Polyester, 8% Elastane', 'Built-in bodice structure', 'Invisible back zip'],
    fabricCare: 'Dry clean recommended.',
    category: 'dresses',
    subcategory: 'Party Dresses',
    collections: ['party-edits', 'best-sellers'],
    price: 3799,
    salePrice: 2999,
    discountPercentage: 21,
    rating: 4.9,
    reviewCount: 49,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isSale: true,
    sku: 'ACE-DRS-005',
    createdAt: '2026-01-25T10:00:00.000Z',
    colors: [
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Red',
        code: '#9E2A2B',
        images: [
          'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 5 },
      { size: 'S', stock: 10 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 8 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-12',
    slug: 'slip-camisole-midi-dress',
    name: 'Liquid Satin Camisole Slip Dress',
    description: 'Classic bias-cut slip dress featuring thin spaghetti straps and a soft scoop neck. Beautiful on its own or under a blazer.',
    details: ['100% Silky Satin Poly', 'Adjustable straps', 'Bias cut drape'],
    fabricCare: 'Hand wash cold.',
    category: 'dresses',
    subcategory: 'Midi Dresses',
    collections: ['party-edits', 'everyday-essentials'],
    price: 3299,
    rating: 4.8,
    reviewCount: 31,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isSale: false,
    sku: 'ACE-DRS-006',
    createdAt: '2026-02-05T10:00:00.000Z',
    colors: [
      {
        name: 'Champagne',
        code: '#F7E7CE',
        images: [
          'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 6 },
      { size: 'S', stock: 14 },
      { size: 'M', stock: 19 },
      { size: 'L', stock: 9 },
      { size: 'XL', stock: 3 },
      { size: 'XXL', stock: 0 },
    ],
  },

  // BOTTOMS (8 products)
  {
    id: 'prod-13',
    slug: 'pleated-wide-leg-tailored-trousers',
    name: 'High-Waist Wide Leg Trousers',
    description: 'Impeccably tailored trousers with front pleats, slant pockets, and a high-rise waistline that elongates the frame.',
    details: ['76% Polyester, 20% Rayon, 4% Spandex', 'Double hook-and-bar closure', 'Wide leg silhouette'],
    fabricCare: 'Dry clean or machine wash cold on delicate cycle.',
    category: 'bottoms',
    subcategory: 'Trousers',
    collections: ['best-sellers', 'office-formal', 'everyday-essentials'],
    price: 2999,
    salePrice: 2499,
    discountPercentage: 17,
    rating: 4.9,
    reviewCount: 75,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isSale: true,
    sku: 'ACE-BTM-001',
    createdAt: '2026-01-20T10:00:00.000Z',
    colors: [
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Beige',
        code: '#D8C9B9',
        images: [
          'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Grey',
        code: '#7D7D7D',
        images: [
          'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 10 },
      { size: 'S', stock: 20 },
      { size: 'M', stock: 25 },
      { size: 'L', stock: 15 },
      { size: 'XL', stock: 8 },
      { size: 'XXL', stock: 3 },
    ],
    reviews: [
      {
        id: 'rev-4',
        userName: 'Ritika S.',
        rating: 5,
        comment: 'These are hands down the best trousers I own for office wear. Fits perfectly high-waisted.',
        createdAt: '2026-03-05',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'prod-14',
    slug: 'vintage-straight-leg-high-waist-jeans',
    name: 'Vintage Straight Leg Denim Jeans',
    description: 'Authentic rigid-look denim featuring a high-rise waist, relaxed straight leg, and raw edge hem detail.',
    details: ['99% Cotton, 1% Elastane', '5-pocket styling', 'Button fly closure'],
    fabricCare: 'Wash inside out in cold water. Do not tumble dry.',
    category: 'bottoms',
    subcategory: 'Jeans',
    collections: ['new-arrivals', 'trending', 'everyday-essentials'],
    price: 3299,
    rating: 4.8,
    reviewCount: 46,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isSale: false,
    sku: 'ACE-BTM-002',
    createdAt: '2026-03-02T10:00:00.000Z',
    colors: [
      {
        name: 'Light Wash Blue',
        code: '#A3B8D7',
        images: [
          'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1582552938357-32b906df40cb?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 7 },
      { size: 'S', stock: 18 },
      { size: 'M', stock: 24 },
      { size: 'L', stock: 12 },
      { size: 'XL', stock: 4 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-15',
    slug: 'relaxed-utility-cargo-pants',
    name: 'Relaxed Fit Utility Cargo Pants',
    description: 'Modern cargo trousers featuring functional flap pockets, adjustable toggle ankles, and a relaxed mid-rise waist.',
    details: ['100% Durable Cotton Twill', 'Multiple utility pockets', 'Drawstring cuffs'],
    fabricCare: 'Machine wash warm with dark colors.',
    category: 'bottoms',
    subcategory: 'Cargo Pants',
    collections: ['casual-chic', 'trending'],
    price: 2799,
    salePrice: 2299,
    discountPercentage: 18,
    rating: 4.7,
    reviewCount: 29,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: false,
    isSale: true,
    sku: 'ACE-BTM-003',
    createdAt: '2026-02-18T10:00:00.000Z',
    colors: [
      {
        name: 'Khaki Green',
        code: '#5B684B',
        images: [
          'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 5 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 16 },
      { size: 'L', stock: 8 },
      { size: 'XL', stock: 3 },
      { size: 'XXL', stock: 1 },
    ],
  },
  {
    id: 'prod-16',
    slug: 'high-waist-satin-midi-skirt',
    name: 'High-Waist Bias Cut Satin Skirt',
    description: 'Sleek satin midi skirt with a clean concealed elastic waistband. Swishes effortlessly with every step.',
    details: ['100% Silky Polyester Satin', 'Bias cut pattern', 'Soft elastic waist'],
    fabricCare: 'Hand wash cold. Cool iron.',
    category: 'bottoms',
    subcategory: 'Skirts',
    collections: ['party-edits', 'office-formal'],
    price: 2299,
    rating: 4.8,
    reviewCount: 35,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isSale: false,
    sku: 'ACE-BTM-004',
    createdAt: '2026-01-30T10:00:00.000Z',
    colors: [
      {
        name: 'Champagne',
        code: '#F7E7CE',
        images: [
          'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1503342394128-c104d54dba01?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 4 },
      { size: 'S', stock: 11 },
      { size: 'M', stock: 15 },
      { size: 'L', stock: 7 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-17',
    slug: 'tailored-high-rise-city-shorts',
    name: 'Tailored High-Rise City Shorts',
    description: 'Chic pleat-front shorts featuring a structured waistband, side pockets, and folded cuffs.',
    details: ['70% Polyester, 26% Rayon, 4% Spandex', 'Front pleat detailing', 'Belt loops'],
    fabricCare: 'Machine wash delicate cold.',
    category: 'bottoms',
    subcategory: 'Shorts',
    collections: ['casual-chic', 'weekend-looks'],
    price: 1899,
    salePrice: 1499,
    discountPercentage: 21,
    rating: 4.6,
    reviewCount: 18,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isSale: true,
    sku: 'ACE-BTM-005',
    createdAt: '2026-02-25T10:00:00.000Z',
    colors: [
      {
        name: 'Beige',
        code: '#E3D8C8',
        images: [
          'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 6 },
      { size: 'S', stock: 10 },
      { size: 'M', stock: 14 },
      { size: 'L', stock: 6 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
  },

  // SETS (8 products)
  {
    id: 'prod-18',
    slug: 'ribbed-knit-co-ord-lounge-set',
    name: 'Ribbed Knit Top & Trousers Co-ord',
    description: 'Chic two-piece set combining a scoop-neck ribbed crop tank with fluid wide-leg knit trousers for luxurious ease.',
    details: ['75% Viscose, 25% Polyester', 'Matching two-piece set', 'Elasticated trousers waistband'],
    fabricCare: 'Hand wash cold or place in garment mesh bag for washing.',
    category: 'sets',
    subcategory: 'Co-ord Sets',
    collections: ['new-arrivals', 'trending', 'casual-chic', 'weekend-looks'],
    price: 4299,
    salePrice: 3599,
    discountPercentage: 16,
    rating: 4.9,
    reviewCount: 54,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: true,
    isSale: true,
    sku: 'ACE-SET-001',
    createdAt: '2026-03-06T10:00:00.000Z',
    colors: [
      {
        name: 'Oatmeal Beige',
        code: '#E3D5C5',
        images: [
          'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Charcoal Grey',
        code: '#363636',
        images: [
          'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1508427953056-b00b8d78ebf5?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 8 },
      { size: 'S', stock: 15 },
      { size: 'M', stock: 20 },
      { size: 'L', stock: 10 },
      { size: 'XL', stock: 4 },
      { size: 'XXL', stock: 1 },
    ],
    reviews: [
      {
        id: 'rev-5',
        userName: 'Kritika B.',
        rating: 5,
        comment: 'Obsessed with this set! So cozy yet looks put together instantly.',
        createdAt: '2026-03-10',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'prod-19',
    slug: 'tailored-blazer-and-skirt-two-piece',
    name: 'Tailored Blazer & Pleated Skirt Set',
    description: 'Polished two-piece set including a cropped single-breasted blazer and a matching high-waisted pleated skirt.',
    details: ['80% Polyester, 18% Viscose, 2% Spandex', 'Structured shoulders', 'Skirt with hidden zip'],
    fabricCare: 'Dry clean only.',
    category: 'sets',
    subcategory: 'Two Piece Sets',
    collections: ['office-formal', 'party-edits'],
    price: 4999,
    rating: 4.8,
    reviewCount: 39,
    isTrending: true,
    isNewArrival: false,
    isBestSeller: true,
    isSale: false,
    sku: 'ACE-SET-002',
    createdAt: '2026-02-12T10:00:00.000Z',
    colors: [
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1551803091-e20673f15770?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Pastel Blue',
        code: '#B2C5DE',
        images: [
          'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1589310243389-96a5483213a8?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 5 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 16 },
      { size: 'L', stock: 8 },
      { size: 'XL', stock: 3 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-20',
    slug: 'breezy-linen-shirt-and-shorts-set',
    name: 'Linen Button-Down & Shorts Set',
    description: 'Relaxed summer co-ord featuring a longline linen button-up shirt paired with matching relaxed elastic shorts.',
    details: ['100% Pure Washed Linen', 'Breathable light weave', 'Adjustable drawstring waist'],
    fabricCare: 'Cool machine wash. Line dry.',
    category: 'sets',
    subcategory: 'Casual Sets',
    collections: ['weekend-looks', 'casual-chic'],
    price: 3699,
    salePrice: 2999,
    discountPercentage: 19,
    rating: 4.7,
    reviewCount: 27,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: false,
    isSale: true,
    sku: 'ACE-SET-003',
    createdAt: '2026-02-22T10:00:00.000Z',
    colors: [
      {
        name: 'Sage Green',
        code: '#8B9B88',
        images: [
          'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'White',
        code: '#FFFFFF',
        images: [
          'https://images.unsplash.com/photo-1598554747436-c9293d6a588f?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 4 },
      { size: 'S', stock: 10 },
      { size: 'M', stock: 14 },
      { size: 'L', stock: 7 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
  },
  {
    id: 'prod-21',
    slug: 'satin-camisole-and-wide-trouser-set',
    name: 'Evening Satin Cami & Trouser Set',
    description: 'Glamorous evening set featuring a subtle cowl neck silk-touch camisole and sleek wide-leg fluid trousers.',
    details: ['100% Liquid Satin', 'Fully adjustable cami straps', 'High waist trousers'],
    fabricCare: 'Dry clean recommended.',
    category: 'sets',
    subcategory: 'Two Piece Sets',
    collections: ['party-edits', 'trending'],
    price: 4599,
    rating: 4.9,
    reviewCount: 42,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isSale: false,
    sku: 'ACE-SET-004',
    createdAt: '2026-03-03T10:00:00.000Z',
    colors: [
      {
        name: 'Midnight Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Mocha Brown',
        code: '#6F4E37',
        images: [
          'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 6 },
      { size: 'S', stock: 12 },
      { size: 'M', stock: 18 },
      { size: 'L', stock: 9 },
      { size: 'XL', stock: 3 },
      { size: 'XXL', stock: 1 },
    ],
  },
  {
    id: 'prod-22',
    slug: 'oversized-sweatshirt-jogger-set',
    name: 'Fleece Oversized Lounge Set',
    description: 'Premium brushed cotton lounge set with a boxy crewneck sweatshirt and high-waisted cuffed joggers.',
    details: ['85% Cotton, 15% Polyester Fleece', 'Deep side pockets on joggers', 'Ribbed cuffs'],
    fabricCare: 'Machine wash warm inside out.',
    category: 'sets',
    subcategory: 'Casual Sets',
    collections: ['casual-chic', 'weekend-looks'],
    price: 3899,
    salePrice: 3199,
    discountPercentage: 18,
    rating: 4.8,
    reviewCount: 61,
    isTrending: false,
    isNewArrival: false,
    isBestSeller: true,
    isSale: true,
    sku: 'ACE-SET-005',
    createdAt: '2026-01-15T10:00:00.000Z',
    colors: [
      {
        name: 'Cream White',
        code: '#F5F5DC',
        images: [
          'https://images.unsplash.com/photo-1554568218-0f1715e72254?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        name: 'Muted Pink',
        code: '#DDA0DD',
        images: [
          'https://images.unsplash.com/photo-1564257631407-4deb1f99d992?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 10 },
      { size: 'S', stock: 18 },
      { size: 'M', stock: 24 },
      { size: 'L', stock: 14 },
      { size: 'XL', stock: 6 },
      { size: 'XXL', stock: 2 },
    ],
  },
  {
    id: 'prod-23',
    slug: 'cropped-corset-top-and-pants-co-ord',
    name: 'Structured Corset & Trousers Set',
    description: 'Statement co-ord features a sweetheart corset crop top with boning accents and tailored straight-leg trousers.',
    details: ['95% Polyester, 5% Elastane', 'Concealed zipper details', 'Boning structure'],
    fabricCare: 'Dry clean recommended.',
    category: 'sets',
    subcategory: 'Co-ord Sets',
    collections: ['party-edits', 'new-arrivals'],
    price: 4799,
    rating: 4.9,
    reviewCount: 22,
    isTrending: true,
    isNewArrival: true,
    isBestSeller: false,
    isSale: false,
    sku: 'ACE-SET-006',
    createdAt: '2026-03-09T10:00:00.000Z',
    colors: [
      {
        name: 'Black',
        code: '#111111',
        images: [
          'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    sizes: [
      { size: 'XS', stock: 4 },
      { size: 'S', stock: 9 },
      { size: 'M', stock: 12 },
      { size: 'L', stock: 6 },
      { size: 'XL', stock: 2 },
      { size: 'XXL', stock: 0 },
    ],
  },
];

export const initialCMS: HomepageCMS = {
  announcementBar: {
    enabled: true,
    text: 'FREE DELIVERY ACROSS NEPAL ON ORDERS ABOVE NPR 3,000 | SHOP NEW ARRIVALS NOW',
  },
  hero: {
    heading: 'YOUR STYLE.\nYOUR STATEMENT.',
    subtitle: 'Discover modern women’s fashion designed for every version of you. Elevated essentials, liquid satin, and precision tailoring.',
    buttonText: 'SHOP NEW ARRIVALS',
    buttonUrl: '/category/new-arrivals',
    secondaryButtonText: 'EXPLORE COLLECTIONS',
    secondaryButtonUrl: '/shop',
    desktopImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=2000&auto=format&fit=crop',
    mobileImage: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
  },
  editorialBanner: {
    heading: 'EFFORTLESSLY YOU',
    subtitle: 'Timeless pieces made for everyday confidence. Clean silhouettes, luxury fabrics, and understated modern elegance.',
    buttonText: 'EXPLORE COLLECTION',
    buttonUrl: '/shop',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=2000&auto=format&fit=crop',
  },
  instagramImages: [
    {
      id: 'ig-1',
      imageUrl: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop',
      postUrl: 'https://www.instagram.com/daisy_hubnp?stkn=MTh4dTQzeGxoMXpnYg==',
    },
    {
      id: 'ig-2',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
      postUrl: 'https://www.instagram.com/daisy_hubnp?stkn=MTh4dTQzeGxoMXpnYg==',
    },
    {
      id: 'ig-3',
      imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop',
      postUrl: 'https://www.instagram.com/daisy_hubnp?stkn=MTh4dTQzeGxoMXpnYg==',
    },
    {
      id: 'ig-4',
      imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800&auto=format&fit=crop',
      postUrl: 'https://www.instagram.com/daisy_hubnp?stkn=MTh4dTQzeGxoMXpnYg==',
    },
    {
      id: 'ig-5',
      imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop',
      postUrl: 'https://www.instagram.com/daisy_hubnp?stkn=MTh4dTQzeGxoMXpnYg==',
    },
    {
      id: 'ig-6',
      imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=800&auto=format&fit=crop',
      postUrl: 'https://www.instagram.com/daisy_hubnp?stkn=MTh4dTQzeGxoMXpnYg==',
    },
  ],
  fonepaySettings: {
    qrMode: 'static',
    qrImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop',
    merchantName: 'DAISY HUB PVT LTD',
    merchantCode: 'DAISY8849',
    accountNumber: '9841234567',
    instructions: 'Scan this official Fonepay QR code using any Mobile Banking app or digital wallet to complete payment.',
    autoVerifyEnabled: true,
  },
};
